<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>10.2.0</Version>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LiteGraph.Sdk\LiteGraph.Sdk.csproj" />
	</ItemGroup>

</Project>


