<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>10.1.0</Version>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteGraph\LiteGraph.csproj" />
    <ProjectReference Include="..\LiteGraph.Server\LiteGraph.Server.csproj" />
    <ProjectReference Include="..\LiteGraph.McpServer\LiteGraph.McpServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.2.0" />
    <PackageReference Include="Voltaic" Version="2.2.1" />
  </ItemGroup>

</Project>

